version: "3.8"
services:
  docker-test-project-redis:
    container_name: docker-test-project-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: kleahwang/docker-test-project-redis
    ports:
      - "6379:6379"
  docker-test-project-database:
    container_name: docker-test-project-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: kleahwang/docker-test-project-database
    environment:
      - MYSQL_DATABASE=docker-test-project
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"